### ISSUE TITLE
Backport for Python 2.7

### ISSUE THREAD

**Issue by Ryuno-Ki** [joernheissler/httplink#1]
Hi @joernheissler,

today I'd like to ask you, whether you would be open to have a second library for Python 2.7 next to the modern implementation.
I already wrote it as part of https://github.com/Ryuno-Ki/webmention-tools/pull/47

So if you are open, I'd create a PR. Otherwise I'd maintain a fork of your great package.

Kind regards

André

**Comment by Ryuno-Ki** [comment]
See https://github.com/joernheissler/httplink/pull/2 if you are interested.

**Comment by joernheissler** [comment]
Hello, and sorry for the **late** response. I didn't really feel like working on my FOSS projects recently.
I also found it hard to make a decision here.

I'm currently working on a patch for another lib where the author still wants to support python 2.6 + 2.7. It's horrible, too many workarounds required.
Frankly, I don't want to actively support py2 if I can help it. In my opinion, people should stop writing more py2 code and instead focus on porting code (and their users) to py3.

I might accept a PR which somehow tweaks the build process to produce two packages, one for py2, one for py3, from the same source code. One tool that might help is https://pypi.org/project/strip-hints/  (never tried it!)

Closing #2 now because that solution doesn't look clean to me.

Of course you're welcome to fork or vendor this library, or take some useful pieces like the regexes.

**Comment by Ryuno-Ki** [comment]
> Hello, and sorry for the late response.

No worries!
Unless Microsoft is shutting down GitHub it is not going anywhere ;-)

Take your time!

> I didn't really feel like working on my FOSS projects recently.

I can emphasize with that.

> Frankly, I don't want to actively support py2 if I can help it.

Can you state that in the README?
This way it is clear that it is a concious choice.

> In my opinion, people should stop writing more py2 code and instead focus on porting code (and their users) to py3.

I agree. However, it has an EOL of 2020. I intend to keep my fork up to that time (and not publish it to PyPI).

> I might accept a PR which somehow tweaks the build process to produce two packages, one for py2, one for py3, from the same source code.

Okay, will look into it somwhen after my vacation.
